apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  # This 'data' section contains configuration keys and values. 
  # When referenced via 'envFrom' in a Deployment, each key becomes an 
  # Environment Variable name, and the value becomes the variable's value.
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # these labels are ReplicaSet labels
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1 # The ReplicaSet ensures that exactly '1' pod is running at all times
  selector:
    # using these labels ReplicaSet selects the pod
    # The ReplicaSet uses these labels to find and manage the pods it owns
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  # This is pod definition, pod is subset of ReplicaSet
  template:
    metadata:
      # Labels applied to the Pods. These must match the selector above.
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  # The service uses this selector to find the active pods created by the 
  # deployment and load balance traffic between them.
  selector:
    # labels are used as selectors to select the pods to 
    # which this service will route the traffic
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672 # servie port
    targetPort: 5672 # container port