apiVersion: v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these labels are ReplicaSet labels
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 1 # The ReplicaSet ensures that exactly '1' pod is running at all times
  selector:
    # using these labels ReplicaSet selects the pods to manage
    # The ReplicaSet uses these labels to find and manage the pods it owns
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  # This is pod definition, pod is subset of ReplicaSet
  template:
    metadata:
      # Labels applied to the Pods. These must match the selector above.
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: mramsudheer/roboshop:mongodb-1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  selector:
  # labels are used as selectors to select the pods to which this service will route the traffic
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port